# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "1.91.0"
    }
  }
}

provider "databricks" {
  alias = "workspace"
}

